project:
  type: website
  output-dir: docs

website:
  title: |
        ![R for Dummies](/images/RforDummies-small-logo.png)
  navbar:
    type: dark
    background: primary
    left:
      - sidebar:about
      - href: reviews.qmd
        text: Reviews
      - href: get-the-book.qmd
        text: Get the book
  body-header: | 
        
  
  sidebar:
    - id: about
      title: "About the book"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: about-the-book.qmd
        - href: table-of-contents.qmd
        - href: about-the-authors.qmd

format:
  html:
    # theme: cosmo
    theme: [cosmo, styles.scss]
    #css: styles.css



